import React from "react";
import { FaRobot, FaChartLine, FaUtensils } from "react-icons/fa";

export default function Features() {
  return (
    <section id="features" className="py-24 bg-white">
      <div className="max-w-7xl mx-auto px-6 text-center">
        <h2 className="text-3xl font-bold mb-12">Features</h2>
        <div className="grid md:grid-cols-3 gap-12">
          <div className="space-y-4 p-6  rounded-lg shadow hover:shadow-lg transition">
            <FaRobot className="text-4xl text-green-600 mx-auto" />
            <h3 className="text-xl font-semibold">AI Meal Suggestions</h3>
            <p className="text-gray-600">
              Get personalized meal plans and recipes generated by AI based on your preferences and goals.
            </p>
          </div>

          <div className="space-y-4 p-6  rounded-lg shadow hover:shadow-lg transition">
            <FaUtensils className="text-4xl text-green-600 mx-auto" />
            <h3 className="text-xl font-semibold">Goal Tracking</h3>
            <p className="text-gray-600">
              Track daily calories, macro & micronutrients, and stay on top of your health objectives.
            </p>
          </div>

          <div className="space-y-4 p-6  rounded-lg shadow hover:shadow-lg transition">
            <FaChartLine className="text-4xl text-green-600 mx-auto" />
            <h3 className="text-xl font-semibold">Analytics Dashboard</h3>
            <p className="text-gray-600">
              Visualize your progress with charts showing daily/weekly nutrient intake vs. goals.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
